const PRIMARY_COLOR = '#2EA2CE';
const BACKGROUND_COLOR = '#FFF';
const TEXT_COLOR_DARK = '#000';
const TEXT_COLOR_LIGHT = '#FFF';
const BACKGROUND_FORM = '#20779B';
const ERROR_TEXT = '#FF0000';

export default {
  PRIMARY_COLOR: PRIMARY_COLOR,
  BACKGROUND_COLOR: BACKGROUND_COLOR,
  TEXT_COLOR_DARK: TEXT_COLOR_DARK,
  TEXT_COLOR_LIGHT: TEXT_COLOR_LIGHT,
  BACKGROUND_FORM: BACKGROUND_FORM,
  ERROR_TEXT: ERROR_TEXT,
};
